# Generated by Django 3.2.13 on 2022-10-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customemail',
            old_name='to_name',
            new_name='from_email',
        ),
        migrations.AddField(
            model_name='customemail',
            name='from_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
