# Generated by Django 3.2.13 on 2022-10-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221013_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemail',
            name='to_email',
            field=models.CharField(max_length=30),
        ),
    ]
