# Generated by Django 3.2.13 on 2022-10-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customemail_to_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customemail',
            old_name='to_email',
            new_name='to_email_address',
        ),
    ]
