# Generated by Django 3.2.13 on 2022-10-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_to_email_customemail_to_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemail',
            name='img',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
