# Generated by Django 3.2.13 on 2022-10-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customemail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemail',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
