# Generated by Django 3.2.13 on 2022-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customemail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemail',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
