# Generated by Django 3.2.13 on 2022-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customemail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemail',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
